### ISSUE TITLE
Lista de palavras: melhorias

### ISSUE THREAD

**Issue by amandalins** [CodeForFloripa/dicionariomanezes#14]
- [x] Não mostrar letras no menu lateral que não possuem verbete. Por exemplo: não existem verbetes iniciados com as letras "K", "Y" e "W", então essas letras não precisariam aparecer no menu lateral. Isso diminuiria o tamanho do menu lateral e deixaria um pouco mais fácil de usar.
- [x] Arrumar scroll do menu lateral: dando scroll totalmente para baixo, a última letra não aparece na tela (ver na imagem). E depois voltando scroll totalmente para cima, a primeira letra não aparece.
  ![dicionario](https://cloud.githubusercontent.com/assets/8741880/17027963/5a5f4dd0-4f3c-11e6-818d-aaee97050e79.png)

**Comment by fgsfabricio** [comment]
- Resolvido o problema da lista do alfabeto sem verbetes correspondentes. Agora o back-end faz uma busca e verifica a letra inicial de cada verbete e adiciona no alfabeto. Caso seja adicionado uma letra nova, ele será adicionado automaticamente.

- Resolvido o problema do espaço na última letra do alfabeto

- Adicionado o item divider para melhorar a usabilidade do usuário. Agora os verbetes são agrupados depois de cada letra do alfabeto no item divider.
![screenshot_20180221-103208](https://user-images.githubusercontent.com/17062940/36483207-443c3e60-16f4-11e8-8011-1bf2d4020fc6.png)
