### ISSUE TITLE
Melhorias no design

### ISSUE THREAD

**Issue by ebonet-zz** [CodeForFloripa/dicionariomanezes#3]
Implementar o design inicial.

**Comment by fgsfabricio** [comment]
Implementado o design da primeira versão do aplicativo. Uma prévia:
![screenshot_20171215-180141](https://user-images.githubusercontent.com/17062940/36483558-4323ef04-16f5-11e8-822b-c6fd2041bc63.png)
![screenshot_20171215-180149](https://user-images.githubusercontent.com/17062940/36483560-44e6bd26-16f5-11e8-919c-073d710e9249.png)
![screenshot_20171215-180325](https://user-images.githubusercontent.com/17062940/36483563-46cf5418-16f5-11e8-871c-f7bfbe62f5af.png)
![screenshot_20171215-180411](https://user-images.githubusercontent.com/17062940/36483565-48377c04-16f5-11e8-9462-53ce5091554c.png)
